In [1]:
import numpy as np
import pandas as pd
import requests
import os

import acquire as a

In [2]:
# https://aphorisms.glitch.me returns a random quotation
response = requests.get('http://aphorisms.glitch.me/')

In [3]:
response

In [4]:
response.ok

True

In [5]:
response.status_code

200

In [6]:
response.text

'{"quote":"Find out who you are and do it on purpose","author":"Dolly Parton"}'

In [7]:
url = 'https://swapi.dev/api/people/5'
response = requests.get(url)
print(response.text)

{"name":"Leia Organa","height":"150","mass":"49","hair_color":"brown","skin_color":"light","eye_color":"brown","birth_year":"19BBY","gender":"female","homeworld":"https://swapi.dev/api/planets/2/","films":["https://swapi.dev/api/films/1/","https://swapi.dev/api/films/2/","https://swapi.dev/api/films/3/","https://swapi.dev/api/films/6/"],"species":[],"vehicles":["https://swapi.dev/api/vehicles/30/"],"starships":[],"created":"2014-12-10T15:20:09.791000Z","edited":"2014-12-20T21:17:50.315000Z","url":"https://swapi.dev/api/people/5/"}

In [8]:
data = response.json()
print(type(data))
data

<class 'dict'>

{'name': 'Leia Organa',
 'height': '150',
 'mass': '49',
 'hair_color': 'brown',
 'skin_color': 'light',
 'eye_color': 'brown',
 'birth_year': '19BBY',
 'gender': 'female',
 'homeworld': 'https://swapi.dev/api/planets/2/',
 'films': ['https://swapi.dev/api/films/1/',
  'https://swapi.dev/api/films/2/',
  'https://swapi.dev/api/films/3/',
  'https://swapi.dev/api/films/6/'],
 'species': [],
 'vehicles': ['https://swapi.dev/api/vehicles/30/'],
 'starships': [],
 'created': '2014-12-10T15:20:09.791000Z',
 'edited': '2014-12-20T21:17:50.315000Z',
 'url': 'https://swapi.dev/api/people/5/'}

In [9]:
root_url = 'https://swapi.dev/api/'
response = requests.get(root_url)
print(response)
response.json()

<Response [200]>

{'people': 'https://swapi.dev/api/people/',
 'planets': 'https://swapi.dev/api/planets/',
 'films': 'https://swapi.dev/api/films/',
 'species': 'https://swapi.dev/api/species/',
 'vehicles': 'https://swapi.dev/api/vehicles/',
 'starships': 'https://swapi.dev/api/starships/'}

In [10]:
response = requests.get('https://swapi.dev/api/people/')

data = response.json()
data.keys()

dict_keys(['count', 'next', 'previous', 'results'])

In [11]:
number_of_people = data['count']
next_page = data['next']
previous_page = data['previous']

print(f'number_of_people: {number_of_people}')
print(f'next_page: {next_page}')
print(f'previous_page: {previous_page}')

number_of_people: 82
next_page: https://swapi.dev/api/people/?page=2
previous_page: None

In [12]:
data['results'][:2]

[{'name': 'Luke Skywalker',
  'height': '172',
  'mass': '77',
  'hair_color': 'blond',
  'skin_color': 'fair',
  'eye_color': 'blue',
  'birth_year': '19BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.dev/api/planets/1/',
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/',
   'https://swapi.dev/api/films/6/'],
  'species': [],
  'vehicles': ['https://swapi.dev/api/vehicles/14/',
   'https://swapi.dev/api/vehicles/30/'],
  'starships': ['https://swapi.dev/api/starships/12/',
   'https://swapi.dev/api/starships/22/'],
  'created': '2014-12-09T13:50:51.644000Z',
  'edited': '2014-12-20T21:17:56.891000Z',
  'url': 'https://swapi.dev/api/people/1/'},
 {'name': 'C-3PO',
  'height': '167',
  'mass': '75',
  'hair_color': 'n/a',
  'skin_color': 'gold',
  'eye_color': 'yellow',
  'birth_year': '112BBY',
  'gender': 'n/a',
  'homeworld': 'https://swapi.dev/api/planets/1/',
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/',
   'https://swapi.dev/api/films/4/',
   'https://swapi.dev/api/films/5/',
   'https://swapi.dev/api/films/6/'],
  'species': ['https://swapi.dev/api/species/2/'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T15:10:51.357000Z',
  'edited': '2014-12-20T21:17:50.309000Z',
  'url': 'https://swapi.dev/api/people/2/'}]

In [13]:
import math

In [14]:
number_of_results = len(data['results'])
max_page = math.ceil(number_of_people / number_of_results)

print(f'number_of_results: {number_of_results}')
print(f'max_page {max_page}')

number_of_results: 10
max_page 9

In [30]:
df = pd.DataFrame(data['results'])
df.head()

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Boba Fett,183,78.2,black,fair,brown,31.5BBY,male,https://swapi.dev/api/planets/10/,"[https://swapi.dev/api/films/2/, https://swapi...",[],[],[https://swapi.dev/api/starships/21/],2014-12-15T12:49:32.457000Z,2014-12-20T21:17:50.349000Z,https://swapi.dev/api/people/22/
1,IG-88,200,140,none,metal,red,15BBY,none,https://swapi.dev/api/planets/28/,[https://swapi.dev/api/films/2/],[https://swapi.dev/api/species/2/],[],[],2014-12-15T12:51:10.076000Z,2014-12-20T21:17:50.351000Z,https://swapi.dev/api/people/23/
2,Bossk,190,113,none,green,red,53BBY,male,https://swapi.dev/api/planets/29/,[https://swapi.dev/api/films/2/],[https://swapi.dev/api/species/7/],[],[],2014-12-15T12:53:49.297000Z,2014-12-20T21:17:50.355000Z,https://swapi.dev/api/people/24/
3,Lando Calrissian,177,79,black,dark,brown,31BBY,male,https://swapi.dev/api/planets/30/,"[https://swapi.dev/api/films/2/, https://swapi...",[],[],[https://swapi.dev/api/starships/10/],2014-12-15T12:56:32.683000Z,2014-12-20T21:17:50.357000Z,https://swapi.dev/api/people/25/
4,Lobot,175,79,none,light,blue,37BBY,male,https://swapi.dev/api/planets/6/,[https://swapi.dev/api/films/2/],[],[],[],2014-12-15T13:01:57.178000Z,2014-12-20T21:17:50.359000Z,https://swapi.dev/api/people/26/

In [16]:
df.shape

(10, 16)

In [17]:
response = requests.get(data['next'])
data = response.json()

number_of_people = data['count']
next_page = data['next']
previous_page = data['previous']
number_of_results = len(data['results'])
max_page = math.ceil(number_of_people / number_of_results)

print(f'number_of_people: {number_of_people}')
print(f'next_page: {next_page}')
print(f'previous_page: {previous_page}')
print(f'number_of_results: {number_of_results}')
print(f'max_page: {max_page}')

df = pd.concat([df, pd.DataFrame(data['results'])]).reset_index()

number_of_people: 82
next_page: https://swapi.dev/api/people/?page=3
previous_page: https://swapi.dev/api/people/?page=1
number_of_results: 10
max_page: 9

In [18]:
response = requests.get(data['next'])
data = response.json()

number_of_people = data['count']
next_page = data['next']
previous_page = data['previous']
number_of_results = len(data['results'])
max_page = math.ceil(number_of_people / number_of_results)

print(f'number_of_people: {number_of_people}')
print(f'next_page: {next_page}')
print(f'previous_page: {previous_page}')
print(f'number_of_results: {number_of_results}')
print(f'max_page: {max_page}')

df = pd.concat([df, pd.DataFrame(data['results'])]).reset_index()

number_of_people: 82
next_page: https://swapi.dev/api/people/?page=4
previous_page: https://swapi.dev/api/people/?page=2
number_of_results: 10
max_page: 9

In [19]:
df.shape

(30, 18)

#### 1. Using the code from the lesson as a guide and the REST API from https://swapi.dev/ as we did in the lesson, create a dataframe named people that has all of the data for people.

In [20]:
a.see_swapi_categories()

dict_keys(['people', 'planets', 'films', 'species', 'vehicles', 'starships'])

In [21]:
people = a.get_swapi_category_data('people')
people.head()

Local file found!

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"['https://swapi.dev/api/films/1/', 'https://sw...",[],"['https://swapi.dev/api/vehicles/14/', 'https:...","['https://swapi.dev/api/starships/12/', 'https...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.dev/api/people/1/
1,C-3PO,167,75,NaN,gold,yellow,112BBY,NaN,https://swapi.dev/api/planets/1/,"['https://swapi.dev/api/films/1/', 'https://sw...",['https://swapi.dev/api/species/2/'],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.dev/api/people/2/
2,R2-D2,96,32,NaN,"white, blue",red,33BBY,NaN,https://swapi.dev/api/planets/8/,"['https://swapi.dev/api/films/1/', 'https://sw...",['https://swapi.dev/api/species/2/'],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.dev/api/people/3/
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.dev/api/planets/1/,"['https://swapi.dev/api/films/1/', 'https://sw...",[],[],['https://swapi.dev/api/starships/13/'],2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.dev/api/people/4/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,"['https://swapi.dev/api/films/1/', 'https://sw...",[],['https://swapi.dev/api/vehicles/30/'],[],2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.dev/api/people/5/

In [22]:
people.shape

(82, 16)

#### 2. Do the same thing, but for planets.

In [23]:
planets = a.get_swapi_category_data('planets')

Local file found!

In [24]:
planets.head()

,name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents,films,created,edited,url
0,Tatooine,23,304,10465,arid,1 standard,desert,1,200000,"['https://swapi.dev/api/people/1/', 'https://s...","['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-09T13:50:49.641000Z,2014-12-20T20:58:18.411000Z,https://swapi.dev/api/planets/1/
1,Alderaan,24,364,12500,temperate,1 standard,"grasslands, mountains",40,2000000000,"['https://swapi.dev/api/people/5/', 'https://s...","['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-10T11:35:48.479000Z,2014-12-20T20:58:18.420000Z,https://swapi.dev/api/planets/2/
2,Yavin IV,24,4818,10200,"temperate, tropical",1 standard,"jungle, rainforests",8,1000,[],['https://swapi.dev/api/films/1/'],2014-12-10T11:37:19.144000Z,2014-12-20T20:58:18.421000Z,https://swapi.dev/api/planets/3/
3,Hoth,23,549,7200,frozen,1.1 standard,"tundra, ice caves, mountain ranges",100,unknown,[],['https://swapi.dev/api/films/2/'],2014-12-10T11:39:13.934000Z,2014-12-20T20:58:18.423000Z,https://swapi.dev/api/planets/4/
4,Dagobah,23,341,8900,murky,NaN,"swamp, jungles",8,unknown,[],"['https://swapi.dev/api/films/2/', 'https://sw...",2014-12-10T11:42:22.590000Z,2014-12-20T20:58:18.425000Z,https://swapi.dev/api/planets/5/

#### 3. Extract the data for starships.

In [25]:
starships = a.get_swapi_category_data('starships')

Local file found!

In [26]:
starships.head()

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films,created,edited,url
0,CR90 corvette,CR90 corvette,Corellian Engineering Corporation,3500000,150,950,30-165,600,3000000,1 year,2.0,60,corvette,[],"['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-10T14:20:33.369000Z,2014-12-20T21:23:49.867000Z,https://swapi.dev/api/starships/2/
1,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,150000000,"1,600",975,"47,060",NaN,36000000,2 years,2.0,60,Star Destroyer,[],"['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-10T15:08:19.848000Z,2014-12-20T21:23:49.870000Z,https://swapi.dev/api/starships/3/
2,Sentinel-class landing craft,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",240000,38,1000,5,75,180000,1 month,1.0,70,landing craft,[],['https://swapi.dev/api/films/1/'],2014-12-10T15:48:00.586000Z,2014-12-20T21:23:49.873000Z,https://swapi.dev/api/starships/5/
3,Death Star,DS-1 Orbital Battle Station,"Imperial Department of Military Research, Sien...",1000000000000,120000,NaN,"342,953","843,342",1000000000000,3 years,4.0,10,Deep Space Mobile Battlestation,[],['https://swapi.dev/api/films/1/'],2014-12-10T16:36:50.509000Z,2014-12-20T21:26:24.783000Z,https://swapi.dev/api/starships/9/
4,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,100000,34.37,1050,4,6,100000,2 months,0.5,75,Light freighter,"['https://swapi.dev/api/people/13/', 'https://...","['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,https://swapi.dev/api/starships/10/

#### 4. Save the data in your files to local csv files so that it will be faster to access in the future.

See acquire.py 'get_swapi_category_data()''

#### 5. Combine the data from your three separate dataframes into one large dataframe.

In [27]:
star_wars = pd.concat([people, planets, starships])
star_wars.head().T

,0,1,2,3,4
name,Luke Skywalker,C-3PO,R2-D2,Darth Vader,Leia Organa
height,172,167,96,202,150
mass,77,75,32,136,49
hair_color,blond,NaN,NaN,none,brown
skin_color,fair,gold,"white, blue",white,light
eye_color,blue,yellow,red,yellow,brown
birth_year,19BBY,112BBY,33BBY,41.9BBY,19BBY
gender,male,NaN,NaN,male,female
homeworld,https://swapi.dev/api/planets/1/,https://swapi.dev/api/planets/1/,https://swapi.dev/api/planets/8/,https://swapi.dev/api/planets/1/,https://swapi.dev/api/planets/2/
films,"['https://swapi.dev/api/films/1/', 'https://sw...","['https://swapi.dev/api/films/1/', 'https://sw...","['https://swapi.dev/api/films/1/', 'https://sw...","['https://swapi.dev/api/films/1/', 'https://sw...","['https://swapi.dev/api/films/1/', 'https://sw..."
species,[],['https://swapi.dev/api/species/2/'],['https://swapi.dev/api/species/2/'],[],[]
vehicles,"['https://swapi.dev/api/vehicles/14/', 'https:...",[],[],[],['https://swapi.dev/api/vehicles/30/']
starships,"['https://swapi.dev/api/starships/12/', 'https...",[],[],['https://swapi.dev/api/starships/13/'],[]
created,2014-12-09T13:50:51.644000Z,2014-12-10T15:10:51.357000Z,2014-12-10T15:11:50.376000Z,2014-12-10T15:18:20.704000Z,2014-12-10T15:20:09.791000Z
edited,2014-12-20T21:17:56.891000Z,2014-12-20T21:17:50.309000Z,2014-12-20T21:17:50.311000Z,2014-12-20T21:17:50.313000Z,2014-12-20T21:17:50.315000Z
url,https://swapi.dev/api/people/1/,https://swapi.dev/api/people/2/,https://swapi.dev/api/people/3/,https://swapi.dev/api/people/4/,https://swapi.dev/api/people/5/
rotation_period,NaN,NaN,NaN,NaN,NaN
orbital_period,NaN,NaN,NaN,NaN,NaN
diameter,NaN,NaN,NaN,NaN,NaN
climate,NaN,NaN,NaN,NaN,NaN
gravity,NaN,NaN,NaN,NaN,NaN
terrain,NaN,NaN,NaN,NaN,NaN
surface_water,NaN,NaN,NaN,NaN,NaN
population,NaN,NaN,NaN,NaN,NaN
residents,NaN,NaN,NaN,NaN,NaN
model,NaN,NaN,NaN,NaN,NaN
manufacturer,NaN,NaN,NaN,NaN,NaN
cost_in_credits,NaN,NaN,NaN,NaN,NaN
length,NaN,NaN,NaN,NaN,NaN
max_atmosphering_speed,NaN,NaN,NaN,NaN,NaN
crew,NaN,NaN,NaN,NaN,NaN
passengers,NaN,NaN,NaN,NaN,NaN
cargo_capacity,NaN,NaN,NaN,NaN,NaN
consumables,NaN,NaN,NaN,NaN,NaN
hyperdrive_rating,NaN,NaN,NaN,NaN,NaN
MGLT,NaN,NaN,NaN,NaN,NaN
starship_class,NaN,NaN,NaN,NaN,NaN
pilots,NaN,NaN,NaN,NaN,NaN

#### 6. Acquire the Open Power Systems Data for Germany, which has been rapidly expanding its renewable energy production in recent years. The data set includes country-wide totals of electricity consumption, wind power production, and solar power production for 2006-2017. You can get the data here: https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv

In [28]:
url = 'https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv'
df = pd.read_csv(url)
df.head()

         Date  Consumption  Wind  Solar  Wind+Solar
0  2006-01-01     1069.184   NaN    NaN         NaN
1  2006-01-02     1380.521   NaN    NaN         NaN
2  2006-01-03     1442.533   NaN    NaN         NaN
3  2006-01-04     1457.217   NaN    NaN         NaN
4  2006-01-05     1477.131   NaN    NaN         NaN

In [29]:
a.get_energy_data()

            Date  Consumption     Wind   Solar  Wind+Solar
0     2006-01-01   1069.18400      NaN     NaN         NaN
1     2006-01-02   1380.52100      NaN     NaN         NaN
2     2006-01-03   1442.53300      NaN     NaN         NaN
3     2006-01-04   1457.21700      NaN     NaN         NaN
4     2006-01-05   1477.13100      NaN     NaN         NaN
...          ...          ...      ...     ...         ...
4378  2017-12-27   1263.94091  394.507  16.530     411.037
4379  2017-12-28   1299.86398  506.424  14.162     520.586
4380  2017-12-29   1295.08753  584.277  29.854     614.131
4381  2017-12-30   1215.44897  721.247   7.467     728.714
4382  2017-12-31   1107.11488  721.176  19.980     741.156

[4383 rows x 5 columns]

#### 7. Make sure all the work that you have done above is reproducible. That is, you should put the code above into separate functions in the acquire.py file and be able to re-run the functions and get the same data.

see acquire.py file in this repo.